### ISSUE TITLE
sched flags not working 

### ISSUE THREAD

**Issue by dariovillar** [tehnerd/gnl2go#1]
Hi @kobolog , @tehnerd , thanks for your answers in [this gorb issue](https://github.com/kobolog/gorb/issues/26) . I was reviewing all the useful information you gave to me and now I understand a little more how this works.

I reviewed the changes that @tehnerd made in [this commit](https://github.com/tehnerd/gnl2go/commit/4fcd2c08cf4b262f327242dd5e6aade9652634af) and it seems like it's almost the functionality I was looking for. However, I couldn't make it work: even if I configured the flags, they did not have any effect and the library worked as usual.

The main function I used to test is in this [gist](https://gist.github.com/dariovillar/38f26294b5ebf7b899a4a30d3ab72648) but the output is:
`Prot LocalAddress:Port Scheduler Flags`
`-> RemoteAddress:Port           Forward Weight ActiveConn InActConn`
`UDP  192.168.1.22:50100 sh`
`-> 192.168.1.22:8080            Masq    10     0          0`
`-> 192.168.1.22:8081            Masq    10     0          0`

While if I do it with:
`ipvsadm -A -u 192.168.0.2:50100  -s sh -b sh-fallback`
`ipvsadm -a -u 192.168.0.2:50100 -r 192.168.0.2:40058 -m -w 10`
`ipvsadm -a -u 192.168.0.2:50100 -r 192.168.0.2:40059 -m -w 10`

The output is:
`Prot LocalAddress:Port Scheduler Flags`
`-> RemoteAddress:Port           Forward Weight ActiveConn InActConn`
`UDP  192.168.0.2:50100 sh (sh-fallback)`
`-> 192.168.0.2:40058            Masq    10      0          0`
`-> 192.168.0.2:40059            Masq    10      0          0`
(Note the sh-fallback flag)

Also in the commit the flags are translated to a binary array but it may be mistranslated from the ipvsadm C.
Should it be `IP_VS_SVC_F_SCHED2            = []byte{0, 0, 0, 0, 0, 0, 1, 0} /* scheduler flag 2 */` or
`IP_VS_SVC_F_SCHED2            = []byte{0, 0, 0, 0, 0, 0, 0, 10} /* scheduler flag 2 */` ?

It would also be interesting to be able to use combinations of the flags such as 
`IP_VS_SVC_F_SH_FALLBACK_AND_PORT            = []byte{0, 0, 0, 0, 0, 0, 0, 18} /* scheduler flag 2 */`

**Comment by tehnerd** [comment]
check main.go in examples section for "how to use flags"  (https://github.com/tehnerd/gnl2go/blob/master/example/main.go#L171) 
also output from testrun of this example: https://gist.github.com/tehnerd/23146c6d699907d2a3e62ef6b83f3135
