### ISSUE TITLE
support direct routing mode

### ISSUE THREAD

**Issue by leslie-wang** [tehnerd/gnl2go#4]
I like https://github.com/kobolog/gorb and want to use it in our product. Seems like direct routing mode is missing because of gnl2go. So wonder to know if it can be enhanced for this feature.

**Comment by leslie-wang** [comment]
Seems like enhancement can be adding one line.
const (
        IPVS_MASQUERADING  = 0
        IPVS_TUNNELING     = 2
        **_`IPVS_DIRECTROUTING = 3`_**
)
Not sure if we need other validation for this option or not for now.

**Comment by tehnerd** [comment]
i will look into this in a couple of days (probably on a weekend). but yeah seems like this is the only place where we will need to change

**Comment by tehnerd** [comment]
https://github.com/tehnerd/gnl2go/commit/c11a71d272de51566cd4d119a8a455090ec57753 added support; tested on 4.6 kernel:

ipvsadm -ln
Prot LocalAddress:Port Scheduler Flags
  -> RemoteAddress:Port           Forward Weight ActiveConn InActConn
TCP  192.168.1.1:80 wrr
  -> 127.0.0.11:80                Tunnel  10     0          0
  -> 127.0.0.11:8080              Route   10     0          0  <<< - Direct Routing
  -> 127.0.0.13:80                Tunnel  20     0          0

**Comment by leslie-wang** [comment]
that is great. Thanks
