### ISSUE TITLE
GetPools() and GetPoolForService() does not return service flags

### ISSUE THREAD

**Issue by mqliang** [tehnerd/gnl2go#6]
There is no "Flag []byte" field in Service struct, see

```golang 
type Pool struct {
	Service Service
	Dests   []Dest
}

type Service struct {
	Proto  uint16
	VIP    string
	Port   uint16
	Sched  string
	FWMark uint32
	AF     uint16
}
```

Service flags are really useful, could you please kindly add it? I tried to delve into the code, and quickly realized that it's challenging for me to add it since I don't know how to decode netlink response.

**Comment by tehnerd** [comment]
will look in couple of days

**Comment by mqliang** [comment]
@tehnerd Great thanks! It will definitely hep me a lot. 

Actually, I also tried to seek other puer go ipvs lib. There is a very helpful go netlink lib, see https://github.com/vishvananda/netlink/, and libnetwork has a ipvs lib leveraging on it, see https://github.com/docker/libnetwork/tree/master/ipvs, whose source code is much more readable(most code are borrowed from ipvsadmin's source code actually). 

But unfortunately, https://github.com/docker/libnetwork/tree/master/ipvs only implement Create/Update/Delete methods for Service/Destination, and missing the Get method. 

If you have some bandwidth, I think gnl2go will be much more readable and easier to maintain if you use the https://github.com/vishvananda/netlink lib to send ipvs netlink request. https://github.com/docker/libnetwork/tree/master/ipvs already implement most of methods, you just need to add Get methods, the most challenging part.

**Comment by tehnerd** [comment]
https://github.com/tehnerd/gnl2go/commit/101b5c6e2d44eb00fbfe85917ffc0bf95249977b adds support for flags

tests:

config:
```
ipvsadm -ln
IP Virtual Server version 1.2.1 (size=1048576)
Prot LocalAddress:Port Scheduler Flags
  -> RemoteAddress:Port           Forward Weight ActiveConn InActConn
FWM  2307 wrr persistent 360 ops
  -> 10.0.0.1:0                   Tunnel  1      0          0
  -> 10.0.0.2:0                   Tunnel  1      0          0
  -> 10.0.0.3:0                   Tunnel  1      0          0
```

example:
```
package main

import (
	"fmt"
	"gnl2go/gnl2go"
)

func main() {
	fmt.Println("Get pool example")
	ipvs := new(gnl2go.IpvsClient)
	ipvs.Init()
	defer ipvs.Exit()
	pools, err := ipvs.GetPools()
	if err != nil {
		fmt.Printf("error in getPools()\n")
		return
	}
	for _, v := range pools {
		fmt.Printf("from GetPools: %#v\n", v)
	}
	// AF_INET = 2
	svc := gnl2go.Service{FWMark: 2307, AF: 2}
	pool, err := ipvs.GetPoolForService(svc)
	if err == nil {
		fmt.Printf("\n\nGetPoolForService: %#v\n", pool)
	}
	return
}
```
output:
```
Get pool example
from GetPools: gnl2go.Pool{Service:gnl2go.Service{Proto:0x0, VIP:"", Port:0x0, Sched:"wrr",
 FWMark:0x903, AF:0x2, Flags:[]uint8{0x7, 0x0, 0x0, 0x0, 0xff, 0xff, 0xff, 0xff}}, Dests:
[]gnl2go.Dest{gnl2go.Dest{IP:"10.0.0.3", Weight:1, Port:0x0, AF:0x2}, gnl2go.Dest{IP:"10.0.0.2", 
Weight:1, Port:0x0, AF:0x2}, gnl2go.Dest{IP:"10.0.0.1", Weight:1, Port:0x0, AF:0x2}}}


GetPoolForService: gnl2go.Pool{Service:gnl2go.Service{Proto:0x0, VIP:"", Port:0x0, Sched:"wrr", 
FWMark:0x903, AF:0x2, Flags:[]uint8{0x7, 0x0, 0x0, 0x0, 0xff, 0xff, 0xff, 0xff}}, Dests:
[]gnl2go.Dest{gnl2go.Dest{IP:"10.0.0.3", Weight:1, Port:0x0, AF:0x2}, gnl2go.Dest{IP:"10.0.0.2",
 Weight:1, Port:0x0, AF:0x2}, gnl2go.Dest{IP:"10.0.0.1", Weight:1, Port:0x0, AF:0x2}}}

```
