### ISSUE TITLE
GetPoolForService() should return error if service not exist

### ISSUE THREAD

**Issue by mqliang** [tehnerd/gnl2go#7]
I use `GetPoolForService()` to detect if a Service exist. I expect `GetPoolForService()` to return error if Service not exist. However, it return a Service with attribute I passed in, and error as nil.

Does this works as intended, or is a bug?

**Comment by tehnerd** [comment]
well it's not an error for netlink's point of view to query from non-existing service. i will look if there any hint that service doesnt exists aside from the empty reals list. also you could use GetPools and look if service is in a return slice if you want to achieve this w/ other existing options

**Comment by mqliang** [comment]
close this.
